config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update]
    resources :tracks, only: [:create, :index]
    resources :likes, only: [:create, :destroy]
    resources :follows, only: [:create, :destroy]
    get '/users/:id/stream' => 'users#stream'
    get '/users/:id/liked_tracks' => 'users#liked_tracks'
    get '/users/:id/followed_users' => 'users#followed_users'
    get '/users/:id/followers' => 'users#followers'
    get '/users/:id/uploaded' => 'users#uploaded'
  end

  get '/session/guest/' => 'sessions#guest'
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]
end

app/views/layouts/_form.html.erb
<% action_path, submit_label, div_class = session_url, "Log In", "login" %>
<% if form_type == :new_user %>
<% action_path, submit_label, div_class = users_url, "Sign Up", "signup" %>
<% end %>

<div class="background">
  <div class="<%= div_class %>">
    <%= image_tag("AudioFile-logo.png", height: "250px:", alt: "logo", class: "center-block") %>
    <h3 id="logo-subtitle">A place to share your music</h3>
    <% if form_type == :new_user %>
    <h4 style="color: #D9230F;">Create an account</h4>
    <% end %>
    <form action="<%= action_path %>" method="post">
      <input type="hidden" name="authenticity_token"
             value="<%= form_authenticity_token %>">
      <div class="form-group">
        <label class="sr-only" for="username-field">User name</label>
        <input type="text" name="user[username]" value="<%= @user.username %>"
               class="form-control" id="username-field" placeholder="Username">
      </div>

      <div class="form-group">
        <label class="sr-only" for="password-field">Password</label>
        <input type="password" name="user[password]" class="form-control"
               id="password-field" placeholder="Password">
      </div>

      <% if form_type == :new_user %>
        <div class="form-group">
          <label class="sr-only" for="location-field">Location</label>
          <input type="location" name="user[location]" class="form-control"
                 id="location-field" placeholder="Location">
        </div>
        <input type="hidden"
               name="user[image]"
               value="<%= image_url('default_avatar_photo.jpg') %>">
      <% end %>

      <% if flash[:errors] %>
        <ul class="list-group">
          <% flash[:errors].each do |error| %>
          <li class="list-group-item list-group-item-danger"><%= error %></li>
          <% end %>
        </ul>
      <% end %>
      <button type="submit" class="btn btn-default"><%= submit_label %></button>
    </form>

    <p style="margin-top: 10px;">
      <% if form_type === :new_user %>
        Already have an account? <a href="<%= new_session_url %>">Log in</a>.
      <% else %>
        Don't have an account? <a href="<%= new_user_url %>">Create one</a> or
        <a href="<%= session_guest_url %>">use the guest account</a>.
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AudioFile</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://widget.cloudinary.com/global/all.js">
  </script>
  <script type="text/javascript" charset="utf-8">
    window.CLOUDINARY_OPTIONS = {
      cloud_name: "<%=ENV['cloud_name']%>",
      upload_preset: "<%= ENV['upload_preset'] %>"
    };
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>

</html>